### PR TITLE
Made Base58 Decoding thread safe

### PR DESCRIPTION
**Pull request by i-holo**
* Added lock for ConcurrentDictionary to make Decode method thread safe

### CODE REVIEW

**Comment by i-holo** [comment]
Hi. 
I faced with an issue of running multibase method in different threads. 
There is possible scenario when different threads are trying to use the same value of ConcurrentDictionary that throws an error.

**Comment by tabrath** [comment]
Taking a lock on a concurrent dictionary seems counter-intuitive, but if it solves the threading issue I guess it's ok. Might be a better solution to it, will have to look into that later.

Thanks 👌

**Comment by 0xced** [comment]
@nilfdev What's the exact error which is thrown? I thought I had solved the concurrency issue in pull request #11. Even added a test to make sure that base58 is thread safe: [TestBase58ConcurrentDecoding](https://github.com/multiformats/cs-multibase/blob/v2.0.2/test/Multiformats.Base.Tests/MultibaseTests.cs#L259).

**Comment by i-holo** [comment]
@0xced 

The Thread Safety section on the ConcurrentDictionary MSDN article has this to say:

All public and protected members of ConcurrentDictionary<TKey, TValue> are thread-safe and may be used concurrently from multiple threads. However, members accessed through one of the interfaces the ConcurrentDictionary<TKey, TValue> implements, including extension methods, are not guaranteed to be thread safe and may need to be synchronized by the caller.

will test and make detailed answer soon

**Comment by 0xced** [comment]
@nilfdev Have you been able to reproduce your issue in a sample app or a unit test?

**Comment by 0xced** [comment]
Ping

**Comment by i-holo** [comment]
hi @0xced 
sorry for late reply I put this investigation in a waiting list and just returned to it when you pinged me. 

I am not able to reproduce the issue with unit test or simple console app. 
I did different test already to show you the issue with ConcurrentDictionary
simple test with tasks like 
            tasks.Add(Task.Run(() =>
            {
                var hash = "8Vtkv2tdQ43bNGdWN9vNx9GVS9wrbXHk4ZW8kmucPmaYJwwedXir52kti9wJhcik4HehyqgLrQ1hBuirviLhxgRBNv";
                Multihash.TryParse(hash, MultibaseEncoding.Base58Btc, out Multihash multihash);
            }));

doesn't bring the issue. 
The same behavior is with test console application, Tasks are executed quite smooth, almost one by one. 

the issue is only on live application. 

This multihash functionality is part of API logic, where we generate multihash for each API request.
with load of 10+ users and without locking 
       lock (DecodeMap) 
ConcurrentDictionary in Multiformats.Base.Base58 class I've got the issue described above. 
On that moment .net core version was 2.2. 

I'm not sure if it has the same issue with .net core 3.1 but no one will allow me to do this test on production again. 

By the way with locking the dictionary the issue is not reproduced on live anymore. Is is already passed half of year, without any issues during Multihash generation.

**Pull request merged**
